on: [push, pull_request]

name: Compile installer

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libxft-dev
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release
